### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by jinzezhi** [ifacker/cscan-go#2]
<img width="606" alt="image" src="https://github.com/ifacker/cscan-go/assets/93123422/9b1d136d-882f-40af-8cc6-2dfe546a41a1">
扫描就卡这了，不懂，任何命令都是，卡着

**Comment by ifacker** [comment]
目前我也不太清楚为什么会卡着，不过一般都是第一次启动的时候会卡住，第一次执行完了之后，后面就好了，抱歉

**Comment by ifacker** [comment]
现在找到问题了，已经修复了，可以再试试看，这次应该不会卡主了
